### ISSUE TITLE
Page numbers in URL seem to skip?

### ISSUE THREAD

**Issue by impressivewebs** [marvindanig/ABCD-Animal-Book#3]
Great job on this!

Seems to be an issue with the page numbers in the URL though....

For example, if I start on page 1, then go to page 2, page 3, etc... The number jumps from page 2 to page 4, skipping 3 completely. But then when I go back, it goes back to page 3. This is happening in both Chrome and Firefox on Windows 7. Haven't tested on my Mac.

**Comment by marvindanig** [comment]
Oh that's the expected behavior! 

In the single-page mode -- if you try it on mobile or iPad (portrait mode) -- you'll see that the numbers progress serially. But on desktops or on the iPad (landscape mode), since there are two pages on display (dual-page mode), the url is pinned to only one of the displayed pages... and it does so according to the read direction.

**Comment by impressivewebs** [comment]
Oh, I see. Yeah, I guess that makes sense when showing two pages at once. I guess I didn't realize there were two pages displayed. Ok, thanks!
